---

- name: Create resource group
  azure_rm_resourcegroup:
    name: "{{ item.name }}"
    location: "{{ item.region }}"
    state: "{{ item.state }}"
    tags: "{{ item.tags }}"
  with_items:
    - "{{ azure_resource_group }}"
