---

- name: Create VM
  azure_rm_virtualmachine:
    name: "{{ item.name }}"
    resource_group: "{{ item.resource_group }}"
    vm_size: "{{ item.vm_size }}"
    storage_account: "{{ item.storage_account }}"
    storage_container_name: "{{ item.storage_container_name }}"
    network_interfaces: "{{ item.network_interfaces }}"
    admin_username: "{{ item.admin_username }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: "/home/kaz/.ssh/authorized_keys"
        key_data: "{{ lookup('env', 'SSH_KEY_DATA') }}"
#        key_data: "{{ item.ssh_key_data }}"
    image:
      offer: "{{ item.image.offer }}"
      publisher: "{{ item.image.publisher }}"
      sku: "{{ item.image.sku }}"
      version: "{{ item.image.version }}"
    tags: "{{ item.tags }}"
  with_items:
    - "{{ azure_virtualmachine }}"
